### ISSUE TITLE
ejs does not link with css file

### ISSUE THREAD

**Issue by BoyanLiuu** [mashish584/EP_BACKEND#1]
Hello, right now I have no trouble to run this project locally. Except, there is no css file link to ejs

![1](https://user-images.githubusercontent.com/45325025/71649010-20522080-2cd9-11ea-8f1f-fb8952910b5c.png)

In the layout.pug , you have `link(rel="stylesheet",` `href="/dist/main.css")`   . However I look all over the folder, but I didnt see a file called dist. So I try to changed to   `		<link href="../assets/scss/style.css" rel="stylesheet" type="text/css">`  but it still didnt work. Do you have any idea? Thanks for helping!

**Comment by mashish584** [comment]
@BoyanLiuu sorry for the delay. Will you please tell me what npm script you're running from terminal ?
